# Generated by Django 2.1.2 on 2018-11-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField(blank=True, null=True)),
                ('m_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=255)),
                ('m_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('m_actor', models.TextField(blank=True, null=True)),
                ('m_type', models.CharField(max_length=255)),
                ('m_nation', models.CharField(blank=True, max_length=255, null=True)),
                ('m_data', models.CharField(blank=True, max_length=255, null=True)),
                ('m_length', models.CharField(blank=True, max_length=50, null=True)),
                ('m_tecentlink', models.CharField(blank=True, max_length=255, null=True)),
                ('m_post', models.CharField(blank=True, max_length=255, null=True)),
                ('m_iqylink', models.CharField(blank=True, max_length=255, null=True)),
                ('m_youkulink', models.CharField(blank=True, max_length=255, null=True)),
                ('m_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('u_password', models.IntegerField(blank=True, null=True)),
                ('u_history', models.CharField(blank=True, max_length=255, null=True)),
                ('u_nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('u_gender', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
